/**
 * World land mask shared by the geo blocks: 256×128 equirectangular pixels, 1 bit
 * each (1 = land), row-major from 90°N / 180°W, most significant bit first,
 * base64-packed.
 */
export const LAND_MASK_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wCf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7//3/////8AAAAAAAQAAAAOAAAAAAAAAAAAAAAAAAAD//wf////+AAAPyAAAAAAAA+AAAAAAAAAAAAAAAAAMCwH4//////wAAAeYAAAAAAAAEAAAAAAAAAAAAAAAB4IB7/A/////+AAAAAAAAAAYAAAPYAAAAAAAAAAAAAAA/42/4AA////8AAAAAAAADwAAH//4AAfsAAAAAAAAAA+AAPAAAA////gAAAAAAAA4AAL///AAAAAAAAAAAAAAHv+ej+wAB///0AAAAAAAAGAHR/////8B8AAACAAMAAAI/8HH/4AB///wAAAABYAAMB///////7//EAAQAP//C9R/9uGH8Ab//+AAAAB/4AABj//////////9h8wD/////+HDecDwA//+AAAAAf//GN/3f////////////8D/////////gP8D//AAAAAD//+L//5////////////xh/////////0B8gH/AA/AAA/j+P////////////////AAP///////8eD8Af4ADwAAH+//////////////////4AH////////AwDAA/AAAAAD/n//////////////////wA////////4AHgAB8AAAAAP8f///////////////i/gAAfsD/////gAfgAAAAAAAA/4D//////////////8MAAAAOAD/////AB/4AAAAAAMDPB/////////////8ABgAAABoAB/////AD/wAAAAAAwCcf/////////////gAfAAAAwAAD/////gf/gAAAAABgLB/////////////4AB4AAAAAAAH/////j//gAAAABzA9//////////////lAHAAAAAAAAP/////P//AAAAAGef///////////////8AYAAAAAAAAf///////4AAAAAB7////////////////QBAAAAAAAAB///////gYAAAAAAf///////////////9AAAAAAAAAABf/////7DwAAAAAf////////////////0AAAAAAAAAAD//////8CAAAAAA////+///////////+QAAAAAAAAAAP//////+AAAAAAB///4n8P/////////wAAAAAAAAAAA//////9AAAAAAAH/n/Afj/////////+EAAAAAAAAAAH//////AAAAAAAf8DP8AfH/////////gwAAAAAAAAAAP/////4AAAAAAA/wmPxx+f////////wAAAAAAAAAAAA/////+AAAAAAAD8CEx//5///////+eAIAAAAAAAAAAD/////4AAAAAAAfwARn//j///////wYBgAAAAAAAAAAH/////AAAAAAAA+ACEf//P///////4wMAAAAAAAAAAAP////8AAAAAAAAD/AAA/////////+DBwAAAAAAAAAAA/////gAAAAAAAH/4AAD/////////4BoAAAAAAAAAAAAf///8AAAAAAAA//wAAf/////////wOAAAAAAAAAAAABf///AAAAAAAAH//48B//////////gAAAAAAAAAAAAAA//8cAAAAAAAAf//////////////8AAAAAAAAAAAAAAD/8AYAAAAAAAD//////8////////4AAAAAAAAAAAAAA3/gBgAAAAAAAf////9/5////////AAAAAAAAAAAAAAAv+ACAAAAAAAD/////z/4f//////4AAAAAAAAAAAAAACf4ACAAAAAAAf/////n/kA//////IAAAAAAAAAAAAAAA/AAAAAAAAAD/////+P/8B/////5AAAAAAAAAAAAAAAB+ABgAAAAAAP/////8//wH/+f/8AAAAAAAAAAAAAAAAH4MBgAAAAAA//////z/+AD/w/8gAAAAAAAAAAAAAAAAPxwA4AAAAAD//////n/4AP8B/mAAAAAAAAAAAAAAAAAP+AAAAAAAAP/////+P+AA/gH/ACAAAAAAAAAAAAAAAAP4AAAAAAAA//////8/gAD8AX+AIAAAAAAAAAAAAAAAAD+AAAAAAAD//////54AAHgAP8AAAAAAAAAAAAAAAAAAB4AAAAAAAP//////2AAAeAAvwAAAAAAAAAAAAAAAAAADAAAAAAAA///////gAAA4ACfAAAAAAAAAAAAAAAAAAAGD+4AAAAA//////+8AADgAIwAQAAAAAAAAAAAAAAAAANv/gAAAAD///////wAANAAgABQAAAAAAAAAAAAAAAAAL//AAAAAH//////+AAAEAAAAHAAAAAAAAAAAAAAAAAAH/+AAAAAP//////4AAAQAGAEIAAAAAAAAAAAAAAAAAAf//gAAAAMg/////AAAAADYAwAAAAAAAAAAAAAAAAAAB///AAAAAAAf///8AAAAAGwHAAAAAAAAAAAAAAAAAAAP//8AAAAAAB////AAAAAANB8AAAAAAAAAAAAAAAAAAB///wAAAAAAH///4AAAAAA4P3gAAAAAAAAAAAAAAAAAH///gAAAAAA////AAAAAABw/ECAAAAAAAAAAAAAAAAA////wAAAAAB///4AAAAAADD5gNgAAAAAAAAAAAAAAAB////8AAAAAD///AAAAAAAGBmA/wAAAAAAAAAAAAAAAP////8AAAAAP//8AAAAAAAIAUAfwAAAAAAAAAAAAAAA/////4AAAAAf//wAAAAAAAYAAE/ggAAAAAAAAAAAAAB/////gAAAAB///AAAAAAAAOAAD+AAAAAAAAAAAAAAAD////+AAAAAH//8AAAAAAAAACABMAgAAAAAAAAAAAAAH////wAAAAAP//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAf///+AAAAAA///gAAAAAAAAAAgQAAAAAAAAAAAAAAAA////wAAAAAH//+BAAAAAAAAAHhAAAAAAAAAAAAAAAAD////AAAAAAf//4MAAAAAAAAG8GAAIAAAAAAAAAAAAAD///8AAAAAD///DgAAAAAAAA/84AAAAAAAAAAAAAAAAH///wAAAAAP//4eAAAAAAAAH/7wAAAgAAAAAAAAAAAAP///AAAAAAf/+B4AAAAAAAA///AAAAAAAAAAAAAAAAA///4AAAAAB//4HgAAAAAAAP///AAAAAAAAAAAAAAAAD///gAAAAAD//gcAAAAAAAD///8ACAAAAAAAAAAAAAAP//4AAAAAAP/+BwAAAAAAAf///4AAAAAAAAAAAAAAAA//8AAAAAAA//4HAAAAAAAB////wAAAAAAAAAAAAAAAD//gAAAAAAB/+AAAAAAAAAH////gAAAAAAAAAAAAAAAP/+AAAAAAAH/4AAAAAAAAAf///+AAAAAAAAAAAAAAAB//4AAAAAAAP/gAAAAAAAAA////4AAAAAAAAAAAAAAAH//AAAAAAAA/8AAAAAAAAAD////gAAAAAAAAAAAAAAAf/4AAAAAAAB/gAAAAAAAAAP/P/+AAAAAAAAAAAAAAAB//gAAAAAAAH8AAAAAAAAAA/AP/wAAAAAAAAAAAAAAAH/cAAAAAAAAIAAAAAAAAAADgAv+AAAAAAAAAAAAAAAA/+AAAAAAAAAAAAAAAAAAAAAAAf4AAQAAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAA/gAAgAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAGAADAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAIAAYAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAPgAACAOPh/4AAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAP//gH///////4AAAAAAAAAAAAAAAAfgAAAAAAAAAAHv//+B/////////4AAAAAAAAAAAAAABvAAAAAAED///////4///////////wAAAAAAAAAA8AAE+AAAAAH/////////////////////gAAAAAABYAH//9/4AAAAD/////////////////////4AAAAAH////////8AAAAAf////////////////////+AAAAAH////////sAAAAD//////////////////////wAAAA/////////+AAAwH///////////////////////gAAAYD////////gAAPgR//////////////////////4AAAAAH////////8ODgA///////////////////////AAAAAH//////////4P/////////////////////////AAAAAf/////////////////////////////////////wD/+AA//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==";

export const LAND_MASK_WIDTH = 256;
export const LAND_MASK_HEIGHT = 128;

const BASE64_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
let decoded: Uint8Array | null = null;

/** The mask bytes (8 pixels per byte), decoded on first use. */
export function landMask(): Uint8Array {
  if (decoded) return decoded;
  const body = LAND_MASK_BASE64.replace(/=+$/, "");
  const bytes = new Uint8Array((body.length * 3) >> 2);
  let buffer = 0;
  let bits = 0;
  let index = 0;
  for (let i = 0; i < body.length; i++) {
    buffer = (buffer << 6) | BASE64_CHARS.indexOf(body[i]!);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes[index++] = (buffer >> bits) & 255;
    }
  }
  decoded = bytes;
  return bytes;
}

/** Whether the point at `lat` / `lng` (degrees) is land. */
export function isLand(lat: number, lng: number): boolean {
  let col = Math.floor(((lng + 180) / 360) * LAND_MASK_WIDTH);
  let row = Math.floor(((90 - lat) / 180) * LAND_MASK_HEIGHT);
  col = col < 0 ? 0 : col >= LAND_MASK_WIDTH ? LAND_MASK_WIDTH - 1 : col;
  row = row < 0 ? 0 : row >= LAND_MASK_HEIGHT ? LAND_MASK_HEIGHT - 1 : row;
  const bit = row * LAND_MASK_WIDTH + col;
  return ((landMask()[bit >> 3]! >> (7 - (bit & 7))) & 1) === 1;
}
